### ISSUE TITLE
Icon-only button is not accessible

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-buttons#3]
Since this is not an official DPG pattern we will not fix this in 1.0.

**Comment by davidakennedy** [comment]
I noticed this too as I was using `cf-buttons`.

I don't think we would really need to make code changes. More like just a change to the documentation. Like instead of:

``` html
<a href="#" class="btn">
    <span class="cf-icon cf-icon-search"></span>
</a>
<button class="btn">
    <span class="cf-icon cf-icon-search"></span>
</button>
```

We do this:

``` html
<a href="#" class="btn">
    <span class="cf-icon cf-icon-search"></span>
    <span class="u-visually-hidden">Search</span>
</a>
<button class="btn">
    <span class="cf-icon cf-icon-search"></span>
    <span class="u-visually-hidden">Search</span>
</button>
```

And maybe a sentence that says to make sure to have a text alternative.

Thoughts?

**Comment by himedlooff** [comment]
'zactly! We'll be adding a utilities component soon so cf-buttons should be able to use `.u-visually-hidden` soon!

**Comment by himedlooff** [comment]
This has been fixed when it migrated to cf-core. cf-core has a `.u-visually-hidden` class and the docs have been updated to use it.
