### ISSUE TITLE
Inconsistent padding for super buttons in IE7

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-buttons#32]
![image](https://cloud.githubusercontent.com/assets/1093373/4820173/fc1159c0-5f10-11e4-92af-a1529c06c931.png)

**Comment by Scotchester** [comment]
Mmm... I'd probably call this a wontfix. It's highly unlikely that the two would ever show up next to each other, and in isolation, neither looks "wrong". And the IE7 audience is dwindling.

**Comment by himedlooff** [comment]
Thanks.
