### ISSUE TITLE
btn__link border color is Pacific 80%, design manual links are Pacific 50%

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-buttons#38]
cf-buttons contains a `btn__link` style that is a link that has button associated classes. The underline on the link is set to the background color for a button [here](https://github.com/cfpb/cf-buttons/blob/gh-pages/src/cf-buttons.less#L866).

The design manual shows buttons as having a [Pacific 80% background](http://cfpb.github.io/design-manual/ui-toolkit/buttons.html) on hover, however it also shows links have a [Pacific 50% underline](http://cfpb.github.io/design-manual/ui-toolkit/links.html) on hover. By using the button background as the underline color, the hover state for `btn__link` diverges from that set in the design manual.

Do links have a place in cf-buttons at all? Should they be migrated to cf-typography?

**Comment by himedlooff** [comment]
The reason we made the `__link` modifier was so that we could have a `button` or `input` element that looks like a link. For example:

![image](https://cloud.githubusercontent.com/assets/1093373/7077204/e5a4d27e-dedc-11e4-8c23-f93b93a4bda6.png)

http://codepen.io/himedlooff/pen/QwXdOx

**Comment by anselmbradford** [comment]
@himedlooff Thanks for the background on this.

It seems like the classes should perhaps follow the visual presentation vs the actual implementation, since the appearance variables are tied to choices made in the design manual. For instance, there could be the reverse modifier in place of `btn__link`... e.g. `link__btn` (looks like a link, but is a button behind the scenes)... that would move this to cf-typography where it could make use of the existing link style variables, as opposed to creating new ones here for `btn__link` border styling.

**Comment by himedlooff** [comment]
Another idea is when styling links, also create a `.link` class, and make sure it will work well with any element, like `button`, meaning it overrides the border and background properties.

**Comment by Scotchester** [comment]
I do not think it's a good idea to rename or move this styling.

The original (and still only) purpose of the `btn__link` class was, as shown by Mike, to have buttons that look like links to de-emphasize them in a group with regular buttons. This class should not be used in any other context, so I think the logical place for it is within cf-buttons.

The link-related variables are [in cf-core](https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-vars.less#L61-L68), which is a dependency of cf-buttons, so they can already be used, if desired, to ensure better consistency.

(As an aside, the border-based implementation will be [going away](https://github.com/cfpb/design-manual/issues/244) soonish.)

**Comment by anselmbradford** [comment]
That all makes sense, but just so I'm clear, in the current state of things this is a bug, is that right? The `btn_link` will have the background color of the buttons and that can't be changed through configuration. Or am I missing something?

**Comment by Scotchester** [comment]
Yes, it is a bug. The `btn__link` underline should use the standard link hover color variable, not the button background color variable.
