### ISSUE TITLE
Update CONTRIBUTING.md to give workflow for contributing

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-buttons#39]
While updating this project I realized the `CONTRIBUTING.md` and docs I looked at on http://cfpb.github.io/capital-framework/contributing/ are too generic to guide a contributor in what needs to be done when fixing an issue and contributing to the project. Specifically what installation and grunt commands need to be run (I just happened to know since I've worked on the project before), what needs to happen with the changelog, etc.

**Comment by KimberlyMunoz** [comment]
Moved to https://github.com/cfpb/capital-framework/issues/203
