### ISSUE TITLE
Incorrect Hover State

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cf-buttons#50]
Buttons shouldn't use the link:hover color, the contrast is too low. Should use the same white color as the default state.

**Current Hover State**

<img width="235" alt="screen shot 2015-10-22 at 10 01 03 am" src="https://cloud.githubusercontent.com/assets/1280430/10667182/fb7f51a8-78a3-11e5-9694-3329e4779260.png">

**Correct Hover State**

<img width="240" alt="screen shot 2015-10-22 at 10 02 46 am" src="https://cloud.githubusercontent.com/assets/1280430/10667203/1190d39a-78a4-11e5-81c0-68104048ce31.png">

**Comment by jimmynotjim** [comment]
Assigning to @KimberlyMunoz because she's already working on color issues. From the looks of it, we just need to assign the @button-text var to the hover state instead of inheriting the default link hover color.

**Comment by KimberlyMunoz** [comment]
Moved to Capital Framework
